/*******************************************************************************
*
* プロジェクト : NAM顧問料デイリー算出システム
* 機能名       : 日次SS用外部委託未払計上額接続ファイル作成
*                バッチ(CFRD1510.csh)用SQL
*                SS用中間テーブル2 INSERT_SQL
* ファイル名   : CFRD1510_05insTemp02.sql
*
* 作成日       : 2009/02/28
* 作成者       : SRA米原
* 更新         : 2014-02-10 GUT高 消費税対応
*
*******************************************************************************/
INSERT INTO CFR_TMP_SS02_TBL
SELECT 
	KAI_CODE,
	IN_SYS_CODE,
	IN_SYS_DATE,
	IN_SYS_DATA_NO,
	SWK_ID,
	KESSAN_KBN,
	IN_USR_ID,
/*       2014-02-10 消費税対応 START */
/** 	DEN_NO, **/
	SUBSTR(IN_SYS_DATE,5,4) || TRIM(TO_CHAR(ROWNUM,'0009')) DEN_NO,
/*       2014-02-10 消費税対応 STOP */
	GYO_NO,
	DR_KMK_CODE,
	DR_HKM_CODE,
	DR_BMN_CODE,
	DR_CODE1,
	DR_CODE2,
	DR_CODE3,
	DR_CODE4,
	DR_KIN,
	DR_CUR_CODE,
	DR_CRT_RATE_TYPE,
	DR_CRT_RATE,
	DR_CUR_KIN,
	DR_ZEI_CODE,
	DR_ZEI_KBN,
	DR_ZEI_KIN,
	DR_TEKIYO1,
	DR_TEKIYO2,
	DR_TORI_KBN,
	DR_TORI_CODE,
	CR_KMK_CODE,
	CR_HKM_CODE,
	CR_BMN_CODE,
	CR_CODE1,
	CR_CODE2,
	CR_CODE3,
	CR_CODE4,
	CR_KIN,
	CR_CUR_CODE,
	CR_CRT_RATE_TYPE,
	CR_CRT_RATE,
	CR_CUR_KIN,
	CR_ZEI_CODE,
	CR_ZEI_KBN,
	CR_ZEI_KIN,
	CR_TEKIYO1,
	CR_TEKIYO2,
	CR_TORI_KBN,
	CR_TORI_CODE,
	SWK_JYO1,
	SWK_JYO2,
	SWK_JYO3,
	SWK_JYO4,
	SWK_JYO5,
	KAIKEI_KOUMOKU1,
	KAIKEI_KOUMOKU2,
	KAIKEI_KOUMOKU3,
	KAIKEI_KOUMOKU4,
	KAIKEI_KOUMOKU5,
	KANRI_COMMENT1,
	KANRI_COMMENT2,
	KANRI_COMMENT3,
	KANRI_COMMENT4,
	KANRI_COMMENT5,
	KANRI_COMMENT6,
	KANRI_COMMENT7,
	KANRI_COMMENT8,
	KANRI_COMMENT9,
	KANRI_COMMENT10,
	AUS_FLG_01,
	AU_USR_ID_01,
	AUS_DATE_01,
	AUS_FLG_02,
	AU_USR_ID_02,
	AUS_DATE_02,
	SYO_FLG
/*       2014-02-10 消費税対応 START */
/** FROM CFR_TMP_SS01_TBL **/
FROM 
(SELECT * FROM CFR_TMP_SS03_TBL
ORDER BY
J_CONTRACT_NO,
KAIKEI_KOUMOKU4) CFR_TMP_SS_TBL
/*       2014-02-10 消費税対応 STOP */
;
